name: Mac Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup Crystal
      run: |
        brew install crystal
    - name: Install dependencies
      run: shards install
    - name: compile
      run: make compile
    - uses: actions/upload-artifact@v1
      with:
        name: poddodger-mac
        path: build/poddodger
